PanasonicRequestSheetProject/Controllers/PRController.cs
using Microsoft.Reporting.WebForms;
using PanasonicRequestSheetProject.Controllers.Abstract;
using PanasonicRequestSheetProject.Models.RequestSheet;
using PanasonicRequestSheetProject.Services;
using PanasonicRequestSheetProject.ViewModel;
using System;
using System.Collections.Generic;
using System.IO;
using System.Linq;
using System.Web;
using System.Web.Mvc;

namespace PanasonicRequestSheetProject.Controllers
{
    public class PRController : BaseController
    {
        [HttpGet]
        public ActionResult AttachFileInfo(int parentId)
        {
            var model = new ERS_T_AttachFileTable();
            model.RequestHDRefer = parentId;

            return View(model);
        }

        [HttpGet]
        public void DownloadAttachmentInfo(int id)
        {
            var service = new RequestSheetEntities();
            var model = service.ERS_T_AttachFileTable.FirstOrDefault(m => m.AttachID == id);
            if (model == null)
                throw new Exception("Row not found.");

            Response.ContentType = "application/octet-stream";
            Response.AppendHeader("Content-Disposition", "attachment; filename=" + Path.GetFileName(model.Path));
            Response.WriteFile(model.Path);
            Response.End();
        }

        [HttpPost]
        public ActionResult AttachFileInfoSaveDetail(ERS_T_AttachFileTable model, HttpPostedFileBase file)
        {
            var service = new RequestSheetEntities();

            var date = DateTime.Now;
            model.Active = true;
            model.CreateDate = date;
            model = service.ERS_T_AttachFileTable.Add(model);

            service.SaveChanges();
            var attachmentService = new AttachmentService();
            attachmentService.SyncAttachFileInfo(model.AttachID, file);

            return View("SmartFormSuccess");
        }

        [HttpGet]
        public ActionResult PrintForm(int id)
        {
            var service = new RequestSheetEntities();
            var dsData = service.GetPurchReqForm(id).ToListSafe();
            var dsImages = service.ERS_T_AttachFileTable.Where(m => m.RequestHDRefer == id && (m.OriginFileName.Contains(".png") || m.OriginFileName.Contains(".jpg"))).ToListSafe();
            var dsImageViewModels = new List<PurchReqImagePrintFormViewModel>();


            decimal countDsData = ((decimal)dsData.Count() / 7);
            decimal countDsImages = ((decimal)dsImages.Count() / 4);

            int countDsDataInt = (int)Math.Ceiling(countDsData);
            int countDsImagesInt = (int)Math.Ceiling(countDsImages);

            var maxPage = countDsDataInt > countDsImagesInt ? countDsDataInt : countDsImagesInt;

            var realPageDsInt = 7 * maxPage;
            var addRowDsInt = realPageDsInt - dsData.Count();

            for (var r = 1; r <= addRowDsInt; r++)
            {
                dsData.Add(new GetPurchReqForm_Result());
            }


            var realPageDsImageInt = 4 * maxPage;
            var addRowDsImageInt = realPageDsImageInt - dsImages.Count();

            for (var r = 1; r <= addRowDsImageInt; r++)
            {
                dsImages.Add(new ERS_T_AttachFileTable());
            }

            int i = 1;
            foreach (var row in dsData)
            {
                row.Row = i;
                row.SignatureApp1 = row.SignatureApp1.ToImagePrintForm();
                row.SignatureApp2 = row.SignatureApp2.ToImagePrintForm();
                row.SignatureApp3 = row.SignatureApp3.ToImagePrintForm();
                row.SignatureApp4 = row.SignatureApp4.ToImagePrintForm();
                i++;
            }

            i = 1;
            foreach (var row in dsImages)
            {
                if (!string.IsNullOrEmpty(row.OriginFileName) && !string.IsNullOrEmpty(row.Path))
                {
                    var originalFileName = row.OriginFileName.ToLower();
                    if (originalFileName.Contains(".png") || originalFileName.Contains(".jpg"))
                    {
                        byte[] imageArray = System.IO.File.ReadAllBytes(row.Path);
                        string base64ImageRepresentation = Convert.ToBase64String(imageArray);

                        var dsImageViewModel = new PurchReqImagePrintFormViewModel();
                        dsImageViewModel.Data = base64ImageRepresentation;
                        dsImageViewModel.Description = row.Description;
                        dsImageViewModel.ItemNo = "";
                        dsImageViewModel.Row = i;
                        dsImageViewModels.Add(dsImageViewModel);
                        i++;
                    }
                }
            }

            ReportDataSource[] reportDataSources = null;

            reportDataSources = new ReportDataSource[2];
            reportDataSources[0] = new ReportDataSource("DataSet", dsData);
            reportDataSources[1] = new ReportDataSource("DataSetImage", dsImageViewModels);

            return Report("PRForm", Request, reportDataSources, string.Format("PRForm"), "pdf");

        }
    }
}

PanasonicRequestSheetProject/Views/PR/AttachFileInfo.cshtml
@using Kendo.Mvc.UI;
@using PanasonicRequestSheetProject.Models.RequestSheet
@model ERS_T_AttachFileTable

<form action="@Url.Action("AttachFileInfoSaveDetail", "PR")" method="post" class="container">
    @Html.HiddenFor(m => m.AttachID)
    @Html.HiddenFor(m => m.RequestHDRefer)

    <div class="form-horizontal" style="background:#fff;margin-top:20px;padding:10px">
        <div class="row">
            <div class="col-md-12 col-sm-12 col-xs-12">
                <div class="form-group">
                    <label class="control-label col-xs-4 col-sm-2">Attach File</label>
                    <div class="control-input col-xs-8 col-sm-9 col-md-9">
                        <a href="@Url.Action("DownloadAttachmentInfo", "Attachment")?id=@Model.AttachID" target="_blank">@Model.OriginFileName</a>
                        @(Html.Kendo()
                        .Upload()
                        .Name("file")
                        .Multiple(false)
                        .DropZone(".dropZoneElement")
                        .HtmlAttributes(new { accept = "image/*;capture=camera" });
                                )
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-xs-4 col-sm-2">Item No.</label>
                    <div class="control-input col-xs-8 col-sm-9 col-md-9">
                        @Html.TextBoxFor(m => m.SeqNO, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-xs-4 col-sm-2">Description</label>
                    <div class="control-input col-xs-8 col-sm-9 col-md-9">
                        @Html.TextAreaFor(m => m.Description, new { @class = "form-control" })
                    </div>
                </div>
                <div class="form-group">
                    <label class="control-label col-xs-5 col-sm-5"><p style="color:#ff0000">@ViewData["ErrorMessage"]</p></label>
                </div>
                <hr />
                <div class="col-sm-offset-10" style="padding:10px">
                    <button class="btn btn-success">Save</button>
                </div>
            </div>
        </div>
    </div>
</form>

PanasonicRequestSheetProject/Views/PR/SmartFormSuccess.cshtml
<!DOCTYPE html>
<html>

<head>
    <title></title>
    <meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta http-equiv="X-UA-Compatible" content="IE=edge" />

</head>

<body style="background-color: ffffff;
        margin: 0 !important;
        padding: 0 !important;">

    <table border="0" cellpadding="0" cellspacing="0" width="100%">
        <!-- LOGO -->
        <tr>
            <td bgcolor="#ffffff" align="center">
                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
                    <tr>
                        <td align="center" valign="top" style="padding: 40px 10px 40px 10px;"> </td>
                    </tr>
                </table>
            </td>
        </tr>
        <tr>
            <td bgcolor="#ffffff" align="center" style="padding: 0px 10px 0px 10px;">
                <table border="0" cellpadding="0" cellspacing="0" width="100%" style="max-width: 600px;">
                    <tr>
                        <td bgcolor="#ffffff" align="center" valign="top" style="padding: 40px 20px 20px 20px; border-radius: 4px 4px 0px 0px; color: #111111; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 48px; font-weight: 400; letter-spacing: 4px; line-height: 48px;">
                            <h1 style="font-size: 48px; font-weight: 400; margin: 2;">Successfully</h1>
                        </td>
                    </tr>
                    <tr>
                        <td bgcolor="#ffffff" align="center" valign="top" style="padding: 40px 20px 20px 20px; border-radius: 4px 4px 0px 0px; color: #111111; font-family: 'Lato', Helvetica, Arial, sans-serif; font-size: 48px; font-weight: 400; letter-spacing: 4px; line-height: 48px;">
                        </td>
                    </tr>
                </table>
            </td>
        </tr>
    </table>
</body>

</html>